service: sns-practice

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
    # - Effect: "Allow"
    #   Resource: "*"
    #   Action:
    #     - "sqs:*"

plugins:
  - serverless-plugin-typescript
  # - serverless-offline-sqs
  - serverless-offline-sns
  - serverless-offline

functions:
  hello:
    handler: src/handler.hello
    # events:
    #   - sqs:
    #       arn: arn:aws:sqs:us-east-1:000000000000:demo-queue
  createTopic:
    handler: src/sns/createTopic.handler
    events:
      - http:
          path: /sns/create/topic
          method: POST
  listTopics:
    handler: src/sns/listTopics.handler
    events:
      - http:
          path: /sns/list/topic
          method: GET
  dispatcher:
    handler: src/sns/dispatcher.handler
    events:
      - sns:
          arn: arn:aws:sns:us-east-1:000000000000:Test_Topic
  publish:
    handler: src/sns/publish.handler
    events:
      - http:
          path: /sns/publish
          method: POST
  subscribe:
    handler: src/sns/subscribe.handler
    events:
      - http:
          path: /sns/subscribe
          method: POST
  listSubscriptions:
    handler: src/sns/listSubscriptions.handler
    events:
      - http:
          path: /sns/list/subscription
          method: POST
  createQueue:
    handler: src/sqs/createQueue.handler
    events:
      - http:
          path: /sqs/create
          method: POST
  receiveMessagesFromQueue:
    handler: src/sqs/receiveMessagesFromQueue.handler
    events:
      - http:
          path: /sqs/receive/messages
          method: POST

# resources:
#  Resources:
#     DemoQueue:
#       Type: AWS::SQS::Queue
#       Properties:
#         QueueName: demo-queue
#         VisibilityTimeout: 10
#         MessageRetentionPeriod: 34560

custom:
  serverless-offline-sns:
    host: 0.0.0.0 # Enable plugin to listen on every local address
    sns-subscribe-endpoint: 192.168.1.127 #Host ip address
    sns-endpoint: http://localhost:4566 # Default localstack sns endpoint
#   serverless-offline-sqs:
#     autoCreate: true                 # create queue if not exists
#     apiVersion: '2012-11-05'
#     endpoint: http://localhost:4566
#     region: us-east-1
#     accessKeyId: root
#     secretAccessKey: root
#     skipCacheInvalidation: false
  # serverless-offline-sns:
  #   port: 4566 # a free port for the sns server to run on
  #   debug: false