version: "3"
services:
  redis_db:
    container_name: redis_db
    image: redis:latest
    ports:
      - 6379:6379
  login_app:
    container_name: login_app
    build: .
    ports:
     - 4000:3000
    depends_on:
     - redis_db